### ISSUE TITLE
need the docupentation for build

### ISSUE THREAD

**Issue by dromyun** [maemo-leste/image-builder#2]
I need documentation how to operate in the construction of an image to be able to implement more construction and distribution platforms, I would also need it to be able to contribute in the construction project since I want to build an automated system to be able to help in the project

**Comment by parazyd** [comment]
Hi. Apologies for the delay. There are a couple of places where the SDK is documented.

I'll assume you're interested in ARM builds.

You'll want to have a look at arm-sdk's README: https://git.devuan.org/sdk/arm-sdk/blob/master/README.md

Further on, it's core library is libdevuansdk. I've written some manpages for it, but they aren't completely up to date: https://git.devuan.org/sdk/arm-sdk/blob/master/README.md

Finally, there are a couple of distros that use this build system. For heads I've written a manual you can find at https://heads.dyne.org/wiki/inside-heads.pdf

This should be enough to get you started. Feel free to ask for more info if needed :)

**Comment by dderby** [comment]
@parazyd, I've been meaning to mention to you that https://github.com/parazyd/arm-sdk/tree/master/extra/blends/README refers to a doc that doesn't exist.

@dromyun, TL;DR version to build an N900 dist:
```
git clone --recurse-submodules git@github.com:maemo-leste/image-builder.git
cd image-builder/arm-sdk
./init.sh    # only needed on first run
zsh -f
source sdk
load devuan n900 maemo
build_image_dist
```

**Comment by dromyun** [comment]
the system of packaging of the sdk is autoconfigured with the files of the previous folder or is and to be added for the configuration of the system creator, I refer to the files blend and config

**Comment by dderby** [comment]
@dromyun, I don't entirely understand what you saying or if you are asking something.

To clarify, if you run the git clone with --recurse-submodules as above, it will automatically checkout the submodules and everything will be in the right place.  When you run the build from the arm-sdk directory, it expects blend and config to be in the directory above and will make use of those files automatically.

**Comment by parazyd** [comment]
Closing. There is documentation on the Wiki and in the repo(s).
